### ISSUE TITLE
Problemi di configurazione

### ISSUE THREAD

**Issue by TheDestr0yer** [MainKronos/Sonarr-AnimeDownloader#104]
### Descrizione
> Ho appena scaricato il programma , ho compilato il docker con api etc.. ho aggiunto l anime alla tabella di conversione ma poi non succede piu' nulla , dai log viene ripetuto l errore :

⚠️ Errore di connessione. (HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.188.158:8989/api/tag?apikey=fd24fcf266f040f7a70b4b0c630218 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7917046400>: Failed to resolve 'http' ([Errno -2] Name or service not known)")))
⚠️ Errore di connessione. (HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.188.158:8989/api/tag?apikey=fd24fcf266f040f7a70b4b0c630218 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7916816df0>: Failed to resolve 'http' ([Errno -2] Name or service not known)")))
⚠️ Errore di connessione. (HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.188.158:8989/api/tag?apikey=fd24fcf266f040f7a70b4b0c630218 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f79167f04f0>: Failed to resolve 'http' ([Errno -2] Name or service not known)")))

![4NMcYJJ60u](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/53081713/f9a6bea7-6909-4e7e-a635-b4c214b0faca)

**Comment by MainKronos** [comment]
Da quello che posso notare probabilmente hai inserito male la variabile d'ambiente `SONARR_URL`. Controlla il tuo docker-compose o il comando che hai lanciato per caricare il container.

```yaml
version: '3.9'
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/path/to/data:/script/json/'
      - '/path/to/animeSeries:/tv'
      - '/path/to/downloads:/downloads'
      - '/path/to/connections:/script/connections'
    ports:
      - 'port:5000'
    environment:
      - 'SONARR_URL=http://url:port' # <------------------ questo
      - 'API_KEY=1234567890abcdefghijklmn'
      - 'TZ=Europe/Rome'
      - 'PUID=1000'
      - 'PGID=1000'
    image: 'ghcr.io/mainkronos/anime_downloader:latest'
```


Se ci sono problemi, mandami il comando/docker-compose che hai usato che ci do un occhiata.

**Comment by TheDestr0yer** [comment]
Provato le soluzioni nel link ma niente stesso errore , inoltre ho notato che questo problema lo fa anche se aggiungo altri anime.

**Comment by TheDestr0yer** [comment]
Cambiando i permessi in PUID=0\ PGID=0 adesso scarica rinomina e posta tutti gli episodi , il problema pero' e' che lo fa in ambiente del container , cioe' non me li sposta sul HDD ma ha creato un percorso cartelle uguale a quello sull HDD ma all interno del container , allego screen 
![xugiq8kGDd](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/53081713/d0750131-b6c1-42be-a4e6-978ae42f1455)

**Comment by MainKronos** [comment]
mi invii il file docker-compose che hai usato? Così ci do un occhiata

**Comment by TheDestr0yer** [comment]
version: '3.9'
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/path/to/data:/script/json/'
      - '/path/to/animeSeries:/tv'
      - '/path/to/downloads:/downloads'
      - '/path/to/connections:/script/connections'
    ports:
      - '5000:5000'
    environment:
      - 'SONARR_URL=http://192.168.188.158:8989/'
      - 'API_KEY=XXXXXXXXXX'
      - 'TZ=Europe/Rome'
      - 'PUID=0'
      - 'PGID=0'
    image: 'ghcr.io/mainkronos/anime_downloader:latest'

**Comment by MainKronos** [comment]
Sono scritte male le directory dei volumi.
Ad esempio, nel tuo caso, la riga `/path/to/animeSeries:/tv` deve diventare (probabilmente) `/mnt/Dati/Plex/Serie\ TV:/tv`.

Quindi devi modificare tutte le cartelle prima del simbolo `:` con la directory esterna al container.

Ad esempio:
Sul mio PC voglio che la cartella `/mnt/dati/media/anime` contenga tutti i file scaricati dal programma, allora devo scrivere nel file docker-compose questo: `/mnt/dati/media/anime:/tv`

Altro esempio:
Voglio che sul mio PC la cartella `/mnt/conf/tool` contenga i file di configurazione del container, allora nel file docker-compose questo: `/mnt/conf/tool:/script/json`

Se qualcosa non ti torna dai un occhiata anche alla [documentazione](https://mainkronos.github.io/Sonarr-AnimeDownloader/usage/quickstart/#parametri), li ci sono anche alcuni esempi

**Comment by TheDestr0yer** [comment]
```yaml
version: '3.9'
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/mnt/Dati/Plex/Anime:/tv'
      - '/mnt/Dati/Plex/Sonarr:/downloads'
    ports:
      - '5000:5000'
    environment:
      - 'SONARR_URL=http://192.168.188.158:8989/'
      - 'API_KEY=xxxxxxxxxxxxx'
      - 'TZ=Europe/Rome'
      - 'PUID=0'
      - 'PGID=0'
    image: 'ghcr.io/mainkronos/anime_downloader:latest'
```
Ho provveduto a modificare il docker compose in questo modo , ma anche cosi' i file non vanno sull HDD ma crea il percorso all interno del container.
