### ISSUE TITLE
[BUG] Dev Testing

### ISSUE THREAD

**Issue by grievertime** [MainKronos/Sonarr-AnimeDownloader#115]
### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
🅴🆁🆁🅾🆁: 'episode'
Traceback (most recent call last):
  File "/script/job.py", line 49, in job
    if sonarr.inQueue(episode["ID"]): # Se il file è già in download su Sonarr
  File "/script/utility/sonarr.py", line 204, in inQueue
    return epId in [x["episode"]["id"] for x in sonarrRequests(requests.get)(url)['records']]
  File "/script/utility/sonarr.py", line 204, in <listcomp>
    return epId in [x["episode"]["id"] for x in sonarrRequests(requests.get)(url)['records']]
KeyError: 'episode'

**Comment by MainKronos** [comment]
Quando accade? È un errore che accade ogni volta che scarica un anime? Accade solo per un anime in particolare? Succede quando su Sonarr è in download qualcosa?

**Comment by grievertime** [comment]
> Quando accade? È un errore che accade ogni volta che scarica un anime? Accade solo per un anime in particolare? Succede quando su Sonarr è in download qualcosa?

Scusa, avevo dato per scontato lo facesse con tutti gli anime ma in realtà solo con Demon Slaye S02 DUB ITA
Su Sonarr non è in download.
Accade appena dopo questo messaggio nei log:
```
🔎 Ricerca anime 'Demon Slayer: Kimetsu no Yaiba' stagione 2.
🔎 Ricerca episodio 1, 2, 3, 4, 5, 6, 7.

⚙️ Verifica se l'episodio 𝐒2𝐄1 è disponibile.
```

**Comment by MainKronos** [comment]
Mi puoi allegare il file di log che do un occhiata

**Comment by grievertime** [comment]
certo
[log (1).log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/12537896/log.1.log)

**Comment by MainKronos** [comment]
Dovrei aver corretto il problema nella versione `dev`, ma visto che ho riscritto da zero il nucleo del programma è un po' instabile 
Se la vuoi intanto provare devi cambiare il nome ai volumi:
```yaml
version: '3.9'
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/path/to/data:/src/database'
      - '/path/to/animeSeries:/tv'
      - '/path/to/downloads:/downloads'
      - '/path/to/connections:/src/script'
    ports:
      - 'port:5000'
    environment:
      - 'SONARR_URL=http://url:port'
      - 'API_KEY=1234567890abcdefghijklmn'
      - 'TZ=Europe/Rome'
      - 'PUID=1000'
      - 'PGID=1000'
    image: 'ghcr.io/mainkronos/anime_downloader:latest'
```

Quindi:
- `/script/connections` diventa `/src/script`
- `/script/json` diventa `/src/database`

Aggiungerò prossimamente una pagina nella wiki per aggiornamenti di transizione alla nuova versione
