### ISSUE TITLE
[QUESTION] Web Interface non disponibile

### ISSUE THREAD

**Issue by dadino** [MainKronos/Sonarr-AnimeDownloader#116]
### Descrizione
Ho installato su UnRaid tramite docker compose. Nella pagina docker di unRaid non ho l'opzione per interfaccia grafica e se vado su 192.168.0.30:5500 non c'è nulla.

Questo è il mio file docker

```
version: '3.9'
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/mnt/user/appdata/animedownloader/config:/script/json/'
      - '/mnt/anime:/media'
      - '/mnt/user/downloads/anime:/downloads'
      - '/mnt/user/appdata/animedownloader/connections:/script/connections'
    ports:
      - '5500:5500'
    environment:
      - 'SONARR_URL=http://192.168.0.30:8989'
      - 'API_KEY=keyredatta'
      - 'TZ=Europe/Rome'
      - 'UMASK=000'
      - 'PUID=99'
      - 'PGID=100'
    image: 'ghcr.io/mainkronos/anime_downloader:latest'
```

Dai log vedo che il programma funziona, ho anche provato a creare un table.json a mano per One Piece, ma evidentemente sbaglio qualcosa nella sintassi, perchè vedo questo nel log "❌ La 𝘴𝘵𝘢𝘨𝘪𝘰𝘯𝘦 1 della 𝘴𝘦𝘳𝘪𝘦 'One Piece' non esiste nella 𝗧𝗮𝗯𝗲𝗹𝗹𝗮 𝗗𝗶 𝗖𝗼𝗻𝘃𝗲𝗿𝘀𝗶𝗼𝗻𝗲."
I file nei volumi sono stati creati. 

Non capisco se salto un passaggio per attivare l'interfaccia web su 192.168.0.30:5500

**Comment by MainKronos** [comment]
hai scritto male la porta interna. Prova ad usare questo:
```yaml
version: '3.9'
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/mnt/user/appdata/animedownloader/config:/script/json/'
      - '/mnt/anime:/media'
      - '/mnt/user/downloads/anime:/downloads'
      - '/mnt/user/appdata/animedownloader/connections:/script/connections'
    ports:
      - '5500:5000'
    environment:
      - 'SONARR_URL=http://192.168.0.30:8989'
      - 'API_KEY=keyredatta'
      - 'TZ=Europe/Rome'
      - 'UMASK=000'
      - 'PUID=99'
      - 'PGID=100'
    image: 'ghcr.io/mainkronos/anime_downloader:latest'
```

e poi collegati a 192.168.0.30:5500. In questo modo dovrebbe funzionare.
