### ISSUE TITLE
[QUESTION] Problema Docker su UNRAID

### ISSUE THREAD

**Issue by geenopippo** [MainKronos/Sonarr-AnimeDownloader#144]
### Descrizione
> Salve, sto provando ad utilizzare questo plugin, installandolo su Unraid. Ho modificato il file yml come segue:

```yaml
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/mnt/user/appdata/animedownloader:/src/database'
      - '/mnt/user/media/Anime:/tv'
      - '/mnt/user/download:/downloads'
      - '/path/to/connections:/src/script'
    ports:
      - 'port:5000'
    environment:
      - 'SONARR_URL=192.168.1.113:8989'
      - 'API_KEY=11d44cc3628f4828bede907f1d26c6e8'
      - 'TZ=Europe/Rome'
      - 'PUID=1000'
      - 'PGID=1000'
    image: 'ghcr.io/mainkronos/anime_downloader:latest'
```

Nel momento in cui avvio il deploy dello stack mi da il seguente errore:

**invalid host Port: port**

Come posso risolvere?
Grazie mille per la disponibilità!
    
    

### Conferma di presa visione
- [x] Confermo di aver controllato la sezione [FAQ](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/FAQ.md) e di non aver trovato nessuna soluzione al problema.
- [x] Confermo di aver controllato tra gli [Issue](https://github.com/MainKronos/Sonarr-AnimeDownloader/issues?q=is%3Aissue+label%3A%22help+wanted%22%2Cquestion%2Cdocumentation+-label%3A%22fixed+on+dev%22) e di non aver trovato nessuna soluzione al problema.

**Comment by MainKronos** [comment]
Non hai definito la porta da aprire all'esterno del container, doc [qui](https://mainkronos.github.io/Sonarr-AnimeDownloader/usage/quickstart/#parametri)

prova così:
```yaml
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/mnt/user/appdata/animedownloader:/src/database'
      - '/mnt/user/media/Anime:/tv'
      - '/mnt/user/download:/downloads'
      - '/path/to/connections:/src/script'
    ports:
      - '5555:5000'
    environment:
      - 'SONARR_URL=192.168.1.113:8989'
      - 'API_KEY=11d44cc3628f4828bede907f1d26c6e8'
      - 'TZ=Europe/Rome'
      - 'PUID=1000'
      - 'PGID=1000'
    image: 'ghcr.io/mainkronos/anime_downloader:latest'
```

In questo modo puoi raggiungere il servizio collegandoti alla pagina http://localhost:5555

**Comment by geenopippo** [comment]
Ho provato, ma ora restituisce il seguente errore:

**usermod: no changes
Traceback (most recent call last):
  File "/src/main.py", line 29, in <module>
    main()
  File "/src/main.py", line 10, in main
    core = Core()
  File "/src/components/backend/core/Core.py", line 50, in __init__
    self.tags = tags if tags else Tags(ctx.DATABASE_FOLDER.joinpath('tags.json'))
  File "/src/components/backend/database/Database.py", line 15, in __init__
    if not db.is_file(): raise FileNotFoundError()
FileNotFoundError
ERROR: Successusermod: no changes
Traceback (most recent call last):
  File "/src/main.py", line 29, in <module>
    main()
  File "/src/main.py", line 10, in main
    core = Core()
  File "/src/components/backend/core/Core.py", line 50, in __init__
    self.tags = tags if tags else Tags(ctx.DATABASE_FOLDER.joinpath('tags.json'))
  File "/src/components/backend/database/Database.py", line 15, in __init__
    if not db.is_file(): raise FileNotFoundError()
FileNotFoundError
ERROR: Successusermod: no changes
Traceback (most recent call last):
  File "/src/main.py", line 29, in <module>
    main()
  File "/src/main.py", line 10, in main
    core = Core()
  File "/src/components/backend/core/Core.py", line 50, in __init__
    self.tags = tags if tags else Tags(ctx.DATABASE_FOLDER.joinpath('tags.json'))
  File "/src/components/backend/database/Database.py", line 15, in __init__
    if not db.is_file(): raise FileNotFoundError()
FileNotFoundError
ERROR: Success

-------------------------------------
GID/UID
-------------------------------------
User uid:       1000
User gid:       1000
-------------------------------------




-------------------------------------
GID/UID
-------------------------------------
User uid:       1000
User gid:       1000
-------------------------------------




-------------------------------------
GID/UID
-------------------------------------
User uid:       1000
User gid:       1000
-------------------------------------**

**Comment by MainKronos** [comment]
all'interno della cartella /mnt/user/appdata/animedownloader copiaci questi file: https://github.com/MainKronos/Sonarr-AnimeDownloader/tree/main/src/database

**Comment by geenopippo** [comment]
Purtroppo non è cambiato nulla, questi sono i log:

AnimeDownloader  | usermod: no changes
AnimeDownloader  | Traceback (most recent call last):
AnimeDownloader  |   File "/src/main.py", line 29, in <module>
AnimeDownloader  |     main()
AnimeDownloader  |   File "/src/main.py", line 10, in main
AnimeDownloader  |     core = Core()
AnimeDownloader  |   File "/src/components/backend/core/Core.py", line 50, in __init__
AnimeDownloader  |     self.tags = tags if tags else Tags(ctx.DATABASE_FOLDER.joinpath('tags.json'))
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 18, in __init__
AnimeDownloader  |     self._data = self.read()
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 23, in read
AnimeDownloader  |     return json.load(f)
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
AnimeDownloader  |     return loads(fp.read(),
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
AnimeDownloader  |     return _default_decoder.decode(s)
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
AnimeDownloader  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
AnimeDownloader  |     raise JSONDecodeError("Expecting value", s, err.value) from None
AnimeDownloader  | json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
AnimeDownloader  | 
AnimeDownloader  | 
AnimeDownloader  | -------------------------------------
AnimeDownloader  | GID/UID
AnimeDownloader  | -------------------------------------
AnimeDownloader  | User uid:    1000
AnimeDownloader  | User gid:    1000
AnimeDownloader  | -------------------------------------
AnimeDownloader  | 
AnimeDownloader  | 
AnimeDownloader  | ERROR: Successusermod: no changes
AnimeDownloader  | Traceback (most recent call last):
AnimeDownloader  |   File "/src/main.py", line 29, in <module>
AnimeDownloader  |     main()
AnimeDownloader  |   File "/src/main.py", line 10, in main
AnimeDownloader  |     core = Core()
AnimeDownloader  |   File "/src/components/backend/core/Core.py", line 50, in __init__
AnimeDownloader  |     self.tags = tags if tags else Tags(ctx.DATABASE_FOLDER.joinpath('tags.json'))
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 18, in __init__
AnimeDownloader  |     self._data = self.read()
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 23, in read
AnimeDownloader  |     return json.load(f)
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
AnimeDownloader  |     return loads(fp.read(),
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
AnimeDownloader  |     return _default_decoder.decode(s)
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
AnimeDownloader  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
AnimeDownloader  |     raise JSONDecodeError("Expecting value", s, err.value) from None
AnimeDownloader  | json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
AnimeDownloader  | 
AnimeDownloader  | 
AnimeDownloader  | -------------------------------------
AnimeDownloader  | GID/UID
AnimeDownloader  | -------------------------------------
AnimeDownloader  | User uid:    1000
AnimeDownloader  | User gid:    1000
AnimeDownloader  | -------------------------------------
AnimeDownloader  | 
AnimeDownloader  | 
AnimeDownloader  | ERROR: Successusermod: no changes
AnimeDownloader  | Traceback (most recent call last):
AnimeDownloader  |   File "/src/main.py", line 29, in <module>
AnimeDownloader  |     main()
AnimeDownloader  |   File "/src/main.py", line 10, in main
AnimeDownloader  |     core = Core()
AnimeDownloader  |   File "/src/components/backend/core/Core.py", line 50, in __init__
AnimeDownloader  |     self.tags = tags if tags else Tags(ctx.DATABASE_FOLDER.joinpath('tags.json'))
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 18, in __init__
AnimeDownloader  |     self._data = self.read()
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 23, in read
AnimeDownloader  |     return json.load(f)
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
AnimeDownloader  |     return loads(fp.read(),
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
AnimeDownloader  |     return _default_decoder.decode(s)
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
AnimeDownloader  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
AnimeDownloader  |     raise JSONDecodeError("Expecting value", s, err.value) from None
AnimeDownloader  | json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
AnimeDownloader  | 
AnimeDownloader  | 
AnimeDownloader  | -------------------------------------
AnimeDownloader  | GID/UID
AnimeDownloader  | -------------------------------------
AnimeDownloader  | User uid:    1000
AnimeDownloader  | User gid:    1000
AnimeDownloader  | -------------------------------------
AnimeDownloader  | 
AnimeDownloader  | 
AnimeDownloader  | ERROR: Successusermod: no changes
AnimeDownloader  | Traceback (most recent call last):
AnimeDownloader  |   File "/src/main.py", line 29, in <module>
AnimeDownloader  |     main()
AnimeDownloader  |   File "/src/main.py", line 10, in main
AnimeDownloader  |     core = Core()
AnimeDownloader  |   File "/src/components/backend/core/Core.py", line 49, in __init__
AnimeDownloader  |     self.settings = settings if settings else Settings(ctx.DATABASE_FOLDER.joinpath('settings.json'))
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 18, in __init__
AnimeDownloader  |     self._data = self.read()
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 23, in read
AnimeDownloader  |     return json.load(f)
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
AnimeDownloader  |     return loads(fp.read(),
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
AnimeDownloader  |     return _default_decoder.decode(s)
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
AnimeDownloader  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AnimeDownloader  |   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
AnimeDownloader  |     raise JSONDecodeError("Expecting value", s, err.value) from None
AnimeDownloader  | json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
AnimeDownloader  | 
AnimeDownloader  | 
AnimeDownloader  | -------------------------------------
AnimeDownloader  | GID/UID
AnimeDownloader  | -------------------------------------
AnimeDownloader  | User uid:    1000
AnimeDownloader  | User gid:    1000
AnimeDownloader  | -------------------------------------
AnimeDownloader  | 
AnimeDownloader  |

**Comment by MainKronos** [comment]
sembrerebbe che il file settings.json sia vuoto

**Comment by geenopippo** [comment]
Quindi non ho modo di risolvere?

**Comment by MainKronos** [comment]
No no, un modo si trova 😅.
Sei sicuro di aver copiato i [questi file](https://github.com/MainKronos/Sonarr-AnimeDownloader/tree/main/src/database) ed il loro contenuto nella cartella `/mnt/user/appdata/animedownloader`?

Prova ad aprire il file setting.json e inviami il contenuto

**Comment by geenopippo** [comment]
Si, sono sicuro! Non posso incollare il contenuto perchè troppo lungo, ma è presente del codice.

![image](https://github.com/user-attachments/assets/f5145e37-31b1-4056-b2d2-50102897f7ff)

**Comment by geenopippo** [comment]
Anteprima file json

![image](https://github.com/user-attachments/assets/746f1082-3a82-4a02-8b91-7e7e1c787cca)

**Comment by MainKronos** [comment]
Direi che c'è un problema, il contenuto dei file dovrebbero essere questi:
### connections.json
```json
[]
```
### settings.json
```json
{
	"LogLevel": "DEBUG",
	"MoveEp": true,
	"RenameEp": true,
	"AutoBind": false,
	"ScanDelay": 30,
	"TagsMode": "BLACKLIST"
}
```
### table.json
```json
[]
```
### tags.json
```json
[]
```

**Comment by geenopippo** [comment]
Come posso risolvere? Sarebbe la soluzione migliore per vedere gli anime sul mio server

**Comment by MainKronos** [comment]
basta che sovrascrivi i file che ti ho elencato con il rispettivo contenuto, altrimenti usa la versione dev:

```yaml
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/mnt/user/appdata/animedownloader:/src/database'
      - '/mnt/user/media/Anime:/tv'
      - '/mnt/user/download:/downloads'
      - '/path/to/connections:/src/script'
    ports:
      - '5555:5000'
    environment:
      - 'SONARR_URL=192.168.1.113:8989'
      - 'API_KEY=11d44cc3628f4828bede907f1d26c6e8'
      - 'TZ=Europe/Rome'
      - 'PUID=1000'
      - 'PGID=1000'
    image: 'ghcr.io/mainkronos/anime_downloader:dev'
```

related #140
