### ISSUE TITLE
[BUG] cambio dominio animeworld

### ISSUE THREAD

**Issue by Nikibasso94** [MainKronos/Sonarr-AnimeDownloader#159]
### Livello di Errore:
> _Selezionare solo un livello di errore_
- `🆆🅰🆁🅽🅸🅽🅶`
- `🅰🅻🅴🆁🆃`
- `🅴🆁🆁🅾🆁`
- **`Other`**

### Messaggio di Errore
CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
ERROR    Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/src/components/backend/core/Core.py", line 144, in run
    self.job()
  File "/src/components/backend/core/Core.py", line 167, in job
    missing = self.processor.getData()
  File "/src/components/backend/core/Processor.py", line 36, in getData
    missing = list(map(self.__sortSerie, missing))
  File "/src/components/backend/core/Processor.py", line 272, in __bindUrl
    elem["seasons"] = list(filter(filterSeason, elem["seasons"]))
  File "/src/components/backend/core/Processor.py", line 248, in filterSeason
    res = self.external.find(title, season["number"], elem["tvdbId"])
  File "/src/components/backend/connection/ExternalDB.py", line 68, in find
    res = aw.find(title)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 54, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 49, in wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 116, in find
    data = res.json()
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Informazioni generali
> _Compilare i campi se correlato_

- **Link di AnimeWorld**: 
- https://www.animeworld.ac/
### Descrizione [_Opzionale_]
>programma va in crash da cambio dominio sito,

da https://www.animeworld.so/  a  https://www.animeworld.ac/

**Comment by razorbac91** [comment]
Ero qui per aprire la medesima issue

**Comment by MainKronos** [comment]
Ho fatto una modifica al volo ieri sera sul branch [dev](https://github.com/MainKronos/Sonarr-AnimeDownloader/tree/dev).
Dovrebbe funzionare ma non ho fatto molti test (perchè avevo sonno 😂😅) per utilizzare l'immagine con la nuova modifica utilizzare il tag dev:

 ```yaml
version: '3.9'
services:
  mainkronos:
    container_name: AnimeDownloader
    volumes:
      - '/path/to/data:/src/database'
      - '/path/to/animeSeries:/tv'
      - '/path/to/downloads:/downloads'
      - '/path/to/connections:/src/script'
    ports:
      - 'port:5000'
    environment:
      - 'SONARR_URL=http://url:port'
      - 'API_KEY=1234567890abcdefghijklmn'
      - 'TZ=Europe/Rome'
      - 'PUID=1000'
      - 'PGID=1000'
    image: 'ghcr.io/mainkronos/anime_downloader:dev' # <----- IMPORTANTE
```
