### ISSUE TITLE
[BUG] [Errno 13] Permission denied

### ISSUE THREAD

**Issue by FriendlyButFire** [MainKronos/Sonarr-AnimeDownloader#166]
### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
`Allegato file, TypeError: Object of type PermissionError is not JSON serializable `

### Informazioni generali
- **Nome Anime**:  One Piece
- **Stagione**:  1
- **Episodio**: 2
- **Link di AnimeWorld**: https://www.animeworld.ac/play/one-piece-subita.qzG-LE/HPKmX1

### Descrizione
> Ciao, il programma si riavvia da solo al termine del download dell'episodio, allego file di configurazione:
Tra l'altro noto che quando aggiungo la serie come absolute, mi aggiunge da solo l'altra normale

[log.txt](https://github.com/user-attachments/files/20511670/log.txt)

[table.json](https://github.com/user-attachments/files/20511678/table.json)

[animedownloader.txt](https://github.com/user-attachments/files/20511700/animedownloader.txt) - yaml non permesso, convertito in txt

Grazie mille

**Comment by MainKronos** [comment]
Prova in questo modo:
```yml
services:
  animedownloader:
    image: 'ghcr.io/mainkronos/anime_downloader:latest'
    container_name: animedownloader
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #ports:
    #  - 'port:5000'
    environment:
      SONARR_URL: http://sonarr:8989
      API_KEY: <redacted>
      ANIMEWORLD_URL: https://www.animeworld.ac
      TZ: $TZ
      PUID: 1000
      PGID: 1000
    volumes:
      - $DOCKERDIR/appdata/animedownloader:/src/database #/home/docker/appdata/animedownloader:/src/database
      - $DATADIR/data/media/tv:$DATADIR/data/media/tv # <--- modificato
      - $DOWNLOADSDIR/downloads:$DOWNLOADSDIR/downloads # <--- modificato
      #- $DOCKERDIR/appdata/animedownloader/script:/src/script
    #network_mode: "service:gluetun"
    networks:
      - t3_proxy
    labels:
    # Anime Downloader
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.animedownloader-rtr.entrypoints=websecure"
      - "traefik.http.routers.animedownloader-rtr.rule=Host(`animedownloader.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.animedownloader-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.animedownloader-rtr.service=animedownloader-svc"
      - "traefik.http.services.animedownloader-svc.loadbalancer.server.port=5000"
```

Problema simile affrontato nelle [FAQ](https://mainkronos.github.io/Sonarr-AnimeDownloader/usage/faq/#uso-sonarr-ma-non-con-docker-e-non-so-quale-mount-dovrei-fare)
