### ISSUE TITLE
Non funziona tramite Portainer

### ISSUE THREAD

**Issue by EffeF** [MainKronos/Sonarr-AnimeDownloader#34]
Il mio docker-compose è:
```yml
---
version: "3.8"
services:
  anime:
    image: mainkronos/anime_downloader:latest
    container_name: anime
    hostname: anime
    depends_on:
      - sonarr
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SONARR_URL=http://**********/sonarr/
      - API_KEY=**********
    volumes:
      - /mnt/HDD1/CONFIG/anime:/script/json/
      - /mnt/HDD1/MEDIA/TV:/tv
      - /mnt/HDD1/DOWNLOAD:/downloads
    ports:
      - 5000:5000
    restart: unless-stopped
```

Tramite Portainer, su Raspberry PI, ricevo il seguente errore:
```
Failure
failed to deploy a stack:
Container anime Creating
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /mnt/HDD1/CONFIG/anime
```

A quanto pare, la cartella non esiste, e non la crea, ma se la creo manualmente il container viene creato, ma non funziona e nei log ha il seguente errore:
```
standard_init_linux.go:228: exec user process caused: exec format error
```

Ho provato le vecchie release, e i problemi sono presenti in tutte dalla 1.5.0 in poi, la 1.4.6 funziona.
