### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'json/settings.json'

### ISSUE THREAD

**Issue by powerxale** [MainKronos/Sonarr-AnimeDownloader#35]
### Informazioni generali
N/A

### Livello di Errore:
> _Selezionare solo un livello di errore_
- `🆆🅰🆁🅽🅸🅽🅶`
- `🅰🅻🅴🆁🆃`
- ** `🅴🆁🆁🅾🆁`
- **`Other`**

### Messaggio di Errore
```
Traceback (most recent call last):
  File "/script/main.py", line 14, in <module>
    SETTINGS = ReadSettings()
  File "/script/app/__init__.py", line 210, in ReadSettings
    with open(json_location, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'json/settings.json'
```

### Descrizione [_Opzionale_]
Container ricreato su Raspberry Pi 3B+, versione 1.5.2.

Il container si arresta e il log posta l'errore su descritto.

**Comment by powerxale** [comment]
No, non sostituito nulla, ho solo creato il container, avviato e poi si stoppa in automatico dando quell'errore.

Riguardo il comando che mi hai suggerito, non posso darlo perché la console funziona solamente quando il container è avviato, ma il mio si stoppa immediatamente dopo l'avvio.

**Comment by MainKronos** [comment]
mi puoi scrivere il comando che hai usato per creare il docker?
(es 
```
docker run -d \
    --name=AnimeDownloader \
    -v /path/to/data:/script/json/ \
    -v /path/to/animeSeries:/tv \
    -v /path/to/downloads:/downloads \
    -p {port}:5000 \
    --env SONARR_URL='http://{url}:{port}' \
    --env API_KEY='1234567890abcdefghijklmn' \
    --env CHAT_ID=123456789 \
    --env BOT_TOKEN='123456789:ABCDEFGHIJKLM-abc_AbCdEfGhI12345678' \
    --env TZ=Europe/Rome \
    mainkronos/anime_downloader
```
)
che cosa hai scritto al posto di `-v /path/to/data:/script/json/` ?

**Comment by powerxale** [comment]
Ho usato docker-compose:

```
version: "2.1"
services:
  animedownloader:
      image: mainkronos/anime_downloader
      container_name: AnimeDownloader
      volumes:
           - /applications/animedownloader:/script/json
           - /media/MEDIA/TV Series/:/tv
      environment:
           - SONARR_URL=http://192.168.xx.xx:8989
           - API_KEY=xx
           - CHAT_ID=xx
           - BOT_TOKEN=xx
           - TZ=Europe/Brussels
      ports:
           - 5000:5000
      logging:
          options:
              max-size: '10m'
              max-file: '3'
```
(ho solo oscurato le key)
